### ISSUE TITLE
Error if you dont type full command

### ISSUE THREAD

**Issue by PetteriM1** [Nukkit-coders/mob-plugin#13]
If you just type "/mob spawn" you get this:

[CRITICAL] Unhandled exception executing command 'mob spawn' in mob: java.lang.ArrayIndexOutOfBoundsException: 1
        at de.kniffo80.mobplugin.MobPlugin.onCommand(MobPlugin.java:111)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:247)
        at cn.nukkit.Server.dispatchCommand(Server.java:643)
        at cn.nukkit.Player.handleDataPacket(Player.java:2546)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:1985)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:799)
        at cn.nukkit.Server.start(Server.java:778)
        at cn.nukkit.Server.<init>(Server.java:465)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)

[ALERT] java.lang.ArrayIndexOutOfBoundsException: 1
        at de.kniffo80.mobplugin.MobPlugin.onCommand(MobPlugin.java:111)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:247)
        at cn.nukkit.Server.dispatchCommand(Server.java:643)
        at cn.nukkit.Player.handleDataPacket(Player.java:2546)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:1985)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:799)
        at cn.nukkit.Server.start(Server.java:778)
        at cn.nukkit.Server.<init>(Server.java:465)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)

**Comment by Spitz4478** [comment]
That's an easy one... in MobPlugin.onCommand() method under `case "spawn"` the first line is `String mob = args[1];` But nothing in the previous code ever verified there actually is an args[1] - only args[0] is checked.

**Comment by Spitz4478** [comment]
Super simple fix would be to add: 
`if (args.length == 1) {
    commandSender.sendMessage("/mob spawn <mob> <opt:player> - Spawn a mob");
    break;
}`
right at the beginning of `case "spawn"` to give them a syntax hint and avoid the outofbounds error.

But that fix ignores all the other potential failure cases when a user enters a /mob command. And speaking in more general terms, it's going to be a difficult to read switch case as you add more commands later.

It may be better to move the code block that gives the player the proper syntax for /mob commands into it's own method. Then have the various cases in MobPlugin.onCommand(), including default, call that method if they run into cases where args[0] is not a valid command or args.length is not the correct size for the command.

And you may even consider moving the code for each switch case into their own methods for readability reasons.
