### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nobytede** [Nukkit-coders/mob-plugin#30]
### Nukkit Version and Client Version

* Nukkit Version: 1.2.5
* Client: Windows10

#### Config.yml
entities:
  mob-ai: true
  auto-spawn-tick: 300
  worlds-spawn-disabled: 

max-spawns:
  bat: 1
  blaze: 0
  cave-spider: 0
  chicken: 1
  cow: 1
  creeper: 0
  donkey: 1
  enderman: 0
  ghast: 0
  horse: 1
  iron-golem: 0
  mooshroom: 1
  mule: 1
  ocelot: 0
  pig: 1
  pig-zombie: 0
  rabbit: 1
  silverfish: 0
  sheep: 1
  skeleton: 1
  skeleton-horse: 0
  snow-golem: 0
  spider: 1
  squid: 0
  witch: 0
  wolf: 1
  zombie: 1
  zombie-horse: 0
  zombie-villager: 0

Put config here

```
### Crashdump, Backtrace or Other Files
2017-12-20 21:55:39 [CRITICAL] Welt "world" konnte nicht getickt werden: java.lang.IllegalStateException: Accept exceeded fixed size of 24
2017-12-20 21:55:39 [ALERT] java.lang.IllegalStateException: Accept exceeded fixed size of 24
	at java.util.stream.Nodes$FixedNodeBuilder.accept(Unknown Source)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at cn.nukkit.level.Level.getEntities(Level.java:2102)
	at de.kniffo80.mobplugin.entities.WalkingEntity.checkTarget(WalkingEntity.java:38)
	at de.kniffo80.mobplugin.entities.WalkingEntity.updateMove(WalkingEntity.java:151)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:164)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)
```

**Comment by PetteriM1** [comment]
I got too theese errors some times.

**Comment by PetteriM1** [comment]
This is maybe bug in Nukkit
