### ISSUE TITLE
more errors

### ISSUE THREAD

**Issue by twixi** [Nukkit-coders/mob-plugin#32]
* PE server version v1.2.2
* Client: Android 1.2.7.2

#### Config.yml
entities:
  mob-ai: true
  auto-spawn-tick: 300
  worlds-spawn-disabled: "exampleworld"

max-spawns:
  bat: 5
  blaze: 5
  cave-spider: 5
  chicken: 5
  cow: 5
  creeper: 5
  donkey: 5
  enderman: 5
  ghast: 5
  horse: 5
  iron-golem: 5
  mooshroom: 5
  mule: 5
  ocelot: 5
  pig: 5
  pig-zombie: 5
  rabbit: 5
  silverfish: 5
  sheep: 5
  skeleton: 5
  skeleton-horse: 5
  snow-golem: 5
  spider: 5
  squid: 5
  witch: 5
  wolf: 5
  zombie: 5
  zombie-horse: 5
  zombie-villager: 5

```
### Crashdump, Backtrace or Other Files
`2018-1-9 21:59:13 [CRITICAL] Could not tick level "world": java.util.ConcurrentModificationException
2018-1-9 21:59:13 [ALERT] java.util.ConcurrentModificationException
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at cn.nukkit.level.Level.getEntities(Level.java:2102)
	at de.kniffo80.mobplugin.entities.WalkingEntity.checkTarget(WalkingEntity.java:38)
	at de.kniffo80.mobplugin.entities.monster.walking.Spider.onUpdate(Spider.java:95)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-1-9 22:02:48 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
2018-1-9 22:02:48 [ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:59)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:48)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:44)
	at de.kniffo80.mobplugin.entities.monster.walking.Wolf.attackEntity(Wolf.java:107)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-1-9 22:02:49 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
2018-1-9 22:02:49 [ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:59)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:48)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:44)
	at de.kniffo80.mobplugin.entities.monster.walking.Wolf.attackEntity(Wolf.java:107)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-1-9 22:02:49 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
2018-1-9 22:02:49 [ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:59)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:48)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:44)
	at de.kniffo80.mobplugin.entities.monster.walking.Wolf.attackEntity(Wolf.java:107)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-1-9 22:02:50 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
2018-1-9 22:02:50 [ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:59)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:48)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:44)
	at de.kniffo80.mobplugin.entities.monster.walking.Wolf.attackEntity(Wolf.java:107)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-1-9 22:02:50 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
2018-1-9 22:02:50 [ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:59)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:48)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:44)
	at de.kniffo80.mobplugin.entities.monster.walking.Wolf.attackEntity(Wolf.java:107)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-1-9 22:02:51 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
2018-1-9 22:02:51 [ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:59)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:48)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:44)
	at de.kniffo80.mobplugin.entities.monster.walking.Wolf.attackEntity(Wolf.java:107)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-1-9 22:02:51 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
2018-1-9 22:02:51 [ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:59)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:48)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:44)
	at de.kniffo80.mobplugin.entities.monster.walking.Wolf.attackEntity(Wolf.java:107)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-1-9 22:02:52 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
2018-1-9 22:02:52 [ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:59)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:48)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:44)
	at de.kniffo80.mobplugin.entities.monster.walking.Wolf.attackEntity(Wolf.java:107)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-1-9 22:02:53 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
2018-1-9 22:02:53 [ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:59)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:48)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:44)
	at de.kniffo80.mobplugin.entities.monster.walking.Wolf.attackEntity(Wolf.java:107)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)

2018-1-9 22:02:54 [CRITICAL] Could not tick level "world": java.lang.NullPointerException
2018-1-9 22:02:54 [ALERT] java.lang.NullPointerException
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getMinDamage(WalkingMonster.java:59)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:48)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.getDamage(WalkingMonster.java:44)
	at de.kniffo80.mobplugin.entities.monster.walking.Wolf.attackEntity(Wolf.java:107)
	at de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:167)
	at cn.nukkit.level.Level.doTick(Level.java:803)
	at cn.nukkit.Server.checkTickUpdates(Server.java:934)
	at cn.nukkit.Server.tick(Server.java:1009)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)`

**Comment by PetteriM1** [comment]
Put max spawns just 1, no more

**Comment by PetteriM1** [comment]
Same as #30
