### ISSUE TITLE
Server Closed

### ISSUE THREAD

**Issue by harunresitc** [Nukkit-coders/mob-plugin#35]
When Creeper is close to me the server is shuts down.

Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Jan 19 16:44:01 2018 from 192.168.1.237
pi@raspberrypi:~ $ cd nukkit3
pi@raspberrypi:~/nukkit3 $ sudo java -jar nukkit.jar
Using log level 'INFO'
15:45:09 [INFO] Loading nukkit.yml...
15:45:09 [INFO] Loading server properties...
15:45:09 [INFO] Selected English (eng) as the base language
15:45:09 [INFO] Starting Minecraft: PE server version v1.2.2
15:45:10 [INFO] Opening server on 0.0.0.0:19132
15:45:10 [INFO] This server is running Nukkit version 1.0dev "蘋果(Apple)派(Pie)                                                                             " (API 1.0.0)
15:45:10 [INFO] Nukkit is distributed under the LGPL License
15:45:13 [INFO] Loading recipes...
15:45:13 [INFO] Loaded 415 recipes.
15:45:13 [INFO] Successfully loaded 0 resource packs
15:45:14 [INFO] Loading MobPlugin v1.0
15:45:14 [INFO] Enabling MobPlugin v1.0
15:45:14 [INFO] [MobPlugin] Plugin enabled successful [aiEnabled:true] [autoSpaw                                                                             nTick:300]
15:45:15 [INFO] Preparing level "world"
15:45:15 [INFO] Starting GS4 status listener
15:45:15 [INFO] Setting query port to 19132
15:45:15 [INFO] Query is running on 0.0.0.0:19132
15:45:15 [INFO] Default game type: Survival Mode
15:45:15 [INFO] Done (7.46s)! For help, type "help" or "?"
15:45:29 [INFO] hrc[/192.168.1.241:48351] logged in with entity id 3 at (world, 124.2327, 65.0, 112.4818)
15:45:31 [INFO] hrc joined the game
15:45:36 [EMERGENCY] Exception happened while ticking server
15:45:36 [ALERT] java.lang.NoClassDefFoundError: cn/nukkit/level/Sound
        at de.kniffo80.mobplugin.entities.monster.walking.Creeper.onUpdate(Creeper.java:145)
        at cn.nukkit.level.Level.doTick(Level.java:803)
        at cn.nukkit.Server.checkTickUpdates(Server.java:934)
        at cn.nukkit.Server.tick(Server.java:1009)
        at cn.nukkit.Server.tickProcessor(Server.java:801)
        at cn.nukkit.Server.start(Server.java:780)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.ClassNotFoundException: cn.nukkit.level.Sound
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more

15:45:36 [ALERT]
"threadDeathWatcher-3-1" Id=22 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

"Nukkit Asynchronous Task Handler #4" Id=21 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@41713e
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@41713e
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...

"Nukkit Asynchronous Task Handler #3" Id=20 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@41713e
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@41713e
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...

"Nukkit Asynchronous Task Handler #2" Id=19 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@41713e
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@41713e
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...

"Nukkit Asynchronous Task Handler #1" Id=18 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@41713e
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@41713e
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...

"Nukkit Asynchronous Task Handler #0" Id=17 WAITING on java.util.concurrent.SynchronousQueue$TransferStack@41713e
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@41713e
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...

"nioEventLoopGroup-2-1" Id=16 RUNNABLE (in native)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@cba515
        -  locked java.util.Collections$UnmodifiableSet@12d4583
        -  locked sun.nio.ch.EPollSelectorImpl@bc224d
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:759)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:400)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        ...

"RakNet Thread #13" Id=13 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
        at cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
        at cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
        at cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)

"Console" Id=8 RUNNABLE (in native)
        at java.io.FileInputStream.read0(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:207)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
        -  locked jline.internal.NonBlockingInputStream@1cd7ea5
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
        at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
        -  locked jline.internal.NonBlockingInputStream@1cd7ea5
        at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
        -  locked jline.internal.NonBlockingInputStream@1cd7ea5
        at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2143)
        ...

"NonBlockingInputStreamThread" Id=12 WAITING on jline.internal.NonBlockingInputStream@1cd7ea5 owned by "Console" Id=8
        at java.lang.Object.wait(Native Method)
        -  waiting on jline.internal.NonBlockingInputStream@1cd7ea5
        at jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
        at java.lang.Thread.run(Thread.java:745)

"process reaper" Id=9 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@2d92c4
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@2d92c4
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...

"process reaper" Id=10 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@2d92c4
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@2d92c4
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ...

"Thread-0" Id=7 RUNNABLE
        at java.util.regex.Pattern$CharProperty.match(Pattern.java:3777)
        at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798)
        at java.util.regex.Pattern$Start.match(Pattern.java:3461)
        at java.util.regex.Matcher.search(Matcher.java:1248)
        at java.util.regex.Matcher.find(Matcher.java:637)
        at java.util.regex.Matcher.replaceAll(Matcher.java:951)
        at cn.nukkit.utils.TextFormat.clean(TextFormat.java:172)
        at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:247)
        ...

"Signal Dispatcher" Id=4 RUNNABLE

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@197cc1f
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@197cc1f
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@723d6a
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.Reference$Lock@723d6a
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)

"main" Id=1 RUNNABLE
        at sun.management.ThreadImpl.dumpThreads0(Native Method)
        at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
        at cn.nukkit.utils.Utils.getAllThreadDumps(Utils.java:111)
        at cn.nukkit.Server.tickProcessor(Server.java:816)
        at cn.nukkit.Server.start(Server.java:780)
        at cn.nukkit.Server.<init>(Server.java:471)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)

15:45:36 [INFO] Disabling MobPlugin v1.0
15:45:36 [INFO] [MobPlugin] Plugin disabled successful.
15:45:37 [INFO] hrc left the game
15:45:37 [INFO] hrc[/192.168.1.241:48351] logged out due to Server closed
15:45:37 [INFO] Unloading level "world"
15:45:38 [INFO] Stopping other threads
pi@raspberrypi:~/nukkit3 $

**Comment by PetteriM1** [comment]
You use NukkitX or old Nukkit?

**Comment by SupremeMortal** [comment]
They are using the old plugin on NukkitX

**Comment by PetteriM1** [comment]
Or new plugin in old Nukkit...

"Starting Minecraft: PE server version v1.2.2"

**Comment by SupremeMortal** [comment]
Yeah I got it the wrong way around

**Comment by PetteriM1** [comment]
@harunresitc Download Mob Plugin from here: [https://github.com/Nukkit-coders/mob-plugin/releases/tag/0.1.2](https://github.com/Nukkit-coders/mob-plugin/releases/tag/0.1.2)

**Comment by harunresitc** [comment]
> version
13:00:24 [INFO] This server is running Nukkit 1.0dev 「蘋果(Apple)派(Pie)」 implementing API version 1.0.0 for Minecraft: PE v1.2.2 (protocol version 137)
>

**Comment by harunresitc** [comment]
Is there any stable Nukkit or NukkitX that i can use with mob plugin?

**Comment by SupremeMortal** [comment]
https://ci.potestas.xyz/job/NukkitX/job/master/
