### ISSUE TITLE
PlayerInteractEvent

### ISSUE THREAD

**Issue by augesrob** [Nukkit-coders/mob-plugin#7]
Reported by Nobyte
https://forums.nukkit.io/members/nobyte.5850/

13:57:51 [CRITICAL] "Das Event 'cn.nukkit.event.player.PlayerInteractEvent' konnte nicht zu 'MobPlugin v1.0': null in Zeile de.kniffo80.mobplugin.MobPlugin weitergegeben werden
13:57:51 [ALERT] cn.nukkit.utils.EventException
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
at cn.nukkit.block.BlockPressurePlateBase.onEntityCollide(BlockPressurePlateBase.java:108)
at cn.nukkit.Player.checkBlockCollision(Player.java:1340)
at cn.nukkit.entity.Entity.entityBaseTick(Entity.java:1070)
at cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:197)
at cn.nukkit.Player.onUpdate(Player.java:1603)
at cn.nukkit.level.Level.doTick(Level.java:803)
at cn.nukkit.Server.checkTickUpdates(Server.java:934)
at cn.nukkit.Server.tick(Server.java:1009)
at cn.nukkit.Server.tickProcessor(Server.java:801)
at cn.nukkit.Server.start(Server.java:780)
at cn.nukkit.Server.<init>(Server.java:471)
at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NullPointerException
at de.kniffo80.mobplugin.MobPlugin.PlayerInteractEvent(MobPlugin.java:363)
at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
... 14 more

**Comment by PetteriM1** [comment]
When this issue comes?

**Comment by augesrob** [comment]
Have a animal or mob walk on pressure plate
